# Speech Dispatcher Generic module config for local Qwen3-TTS
Debug 1

GenericExecuteSynth "/home/john/git-projects/qwen3-tts-speech-dispatcher/extras/speech-dispatcher/qwen3-tts-synth-b64.sh \"$DATA\""
GenericCmdDependency "/home/john/anaconda3/envs/qwen3-tts/bin/python"
GenericMaxChunkLength 100000
GenericDelimiters ""

AddVoice "en" "MALE1" "male1"
AddVoice "en" "FEMALE1" "female1"
AddVoice "en-us" "MALE1" "male1"
AddVoice "en-us" "FEMALE1" "female1"
AddVoice "en_US" "MALE1" "male1"
AddVoice "en_US" "FEMALE1" "female1"

GenericLanguage "en_US" "en"
GenericLanguage "en-us" "en"

DefaultVoice "female1"
